### ISSUE TITLE
Is mailbase an external service

### ISSUE THREAD

**Issue by otengkwame** [tkeer/mailbase#11]
Hi,

I want to find out if mailbase is an external service that tracks emails or a php workaround to catch emails in Laravel.

Thank You

**Comment by tkeer** [comment]
Hey, that's a php work around. If you are looking for external services, you may want to look at maildev or mailhog.

**Comment by otengkwame** [comment]
Wow that's great, can  it be used outside Laravel?

**Comment by tkeer** [comment]
No it can't.

**Comment by otengkwame** [comment]
okay cool, thanks for your time
